AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  findcrypto-api

  AWS SAM Template for findcrypto-api

Globals:
  Function:
    Timeout: 3
    Runtime: python3.8
    Architectures:
      - x86_64

Resources:
  GetCmcCryptoCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/cmc/
      Handler: app.lambda_handler
      Events:
        CmcCryptoCategory:
          Type: Api 
          Properties:
            Path: /cmc
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetCmcCryptoCategoryApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GetCmcCryptoCategoryFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt GetCmcCryptoCategoryFunction.Arn
  GetCmcCryptoCategoryFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GetCmcCryptoCategoryFunctionRole.Arn
